### ISSUE TITLE
How to manage a community repair cafe

### ISSUE THREAD

**Issue by Math-TECH-Hub** [ASKnet-Open-Training/CommunityRepairCafe#2]
![Tools 17](https://user-images.githubusercontent.com/57042950/100147219-1b2b3080-2eac-11eb-9783-5f9a9f79ca6a.jpg)
tools well organized in December 2018 during the #ASKnet training at the Refugee CTEN information Rhino

**Comment by timmwille** [comment]
nice @Math-TECH-Hub reminds me of the original documentation we made with @vugawilliam 
https://wikifab.org/wiki/Open_Workshop_Setup

**Comment by timmwille** [comment]
we could also try to find the most important tools of those for small repair café in here
https://github.com/ASKnet-Open-Training/Minimal-Repair-Setup

@maliarich

**Comment by timmwille** [comment]
this is amazing, I just found a great add of notes in one of the origins issues from @dawaedina27 check this out, may someone find a good way to include this in the guide?
https://github.com/Math-TECH-Hub/CommunityRepairCafe/issues/10

**Comment by timmwille** [comment]
![grafik](https://user-images.githubusercontent.com/8081055/105870767-e2691e00-5ff8-11eb-8c49-fb75240f05cc.png)

**Comment by timmwille** [comment]
I guess parts of this Training Event overview also applies to this, right? @ASKnet-Open-Training/team-community-repair-cafe

**Comment by timmwille** [comment]
![grafik](https://user-images.githubusercontent.com/8081055/105870974-1e03e800-5ff9-11eb-9331-121db60a9c55.png)

**Comment by timmwille** [comment]
thx @chardso Wafela I think we can copy your comment over here? https://github.com/ASKnet-Open-Training/CommunityRepairCafe/issues/22#issuecomment-771897702

**Comment by dawaedina27** [comment]
How the event will happen?

At the reception we shall an expert to register the broken devices brought by the community,that's table one.
2 . our experts will be specialised,one will hand solars and radios,the second will handle small electronics such as phones,lighting systems etc.
3 . the third one will handle computer repair and maintainance(both mechanical and soft ware).
4 . fixing of the devices will start after establishing the registered number of devices at the reception.
5 .A support team in which one personnel will have a camera or a smart phone to take the coverage of the activities ie photos,video clips etc.
6 .One person will be doing online documentations such the people away from the site will follow online proceedings and comment where necessary.
7 .Before the everything resumes we shall have an expert who will introduce the set up to our online teams.
8 .One of the expert to interview a community member about how the repair cafe has impacted him/her.
9.comments by teams involved, @ member to write about the activities
10 .Closing remarks by the host.

**Comment by dawaedina27** [comment]
@timmwille I copied @chardso's comments #22

**Comment by dawaedina27** [comment]
Few Tips for starting a Repair Cafe.

1.Visit a couple of established Repair Cafes

2. Don’t get hung up on health and safety and insurance.
> Make sure repairers work within the limits of their skills and, if necessary, get help from
other repairers.
> Explain to owners that you are enthusiastic amateurs not paid professionals (also use a
disclaimer
> Don’t take on a major repair if you’re not happy to do so for any reason. We always say we’re a clinic not a hospital.

3. Get advance bookings

4.Try to make sure your venue allows you to have repairs and waiting area in the same space. This means waiting owners can see what’s going on – that there’s a queue – and don’t feel they are being ignored.

5. Encourage repairers to give a running commentary Owners are expected to stay with their items and the repairers while s/he assesses the problem and talks through any repairs undertaken.
The idea is that the owner leaves knowing more about his/her item than when they arrived. Some Repair Cafes offer ‘skillshare’ sessions to teach DIY repair work.

6. Encourage repairers to be honest about their abilities.

Get owners to sign a ‘disclaimer’ when they arrive. A Repair Cafe should have a set of ‘rules’ that clarifies the relationship between owner and repairer. Ask the owners to read and sign it – it will not stand up in court but helps establish the amateur nature of our (voluntary) work.

7. Do some market research. You can test out the best times and days for running your events.

8. Get feedback We ask attenders to filling in a short series of questions when they leave and also record the success (or otherwise) of assessment and repair. This is useful for publicity, for reporting back to repairers, and useful if you ever need to make a grant application for running costs.

9. Invite donations We alert people in advance to the fact that the event is free, but we appreciate donations to cover insurance, venue hire, refreshments, consumables such as glues and fuses, publicity materials etc

**Comment by chardso** [comment]
@dawaedina27  I truely like what am seeing and we are gonna apply where necessary.
